/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tmp.java
 *
 * Created on Jul 2, 2009, 3:13:00 PM
 */

package bbk.dng.actions;

/**
 *
 * @author Roman
 */
public class Tmp extends javax.swing.JFrame {

    /** Creates new form Tmp */
    public Tmp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nodeDisplaybuttonGroup = new javax.swing.ButtonGroup();
    domainsOnlyRadioButton = new javax.swing.JRadioButton();
    addSequencesRadioButton = new javax.swing.JRadioButton();
    addStructuresRadioButton = new javax.swing.JRadioButton();
    displayOptionsLabel = new javax.swing.JLabel();
    jToggleButton1 = new javax.swing.JToggleButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setName("Form"); // NOI18N

    nodeDisplaybuttonGroup.add(domainsOnlyRadioButton);
    domainsOnlyRadioButton.setSelected(true);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(bbk.dng.Main.class).getContext().getResourceMap(Tmp.class);
    domainsOnlyRadioButton.setText(resourceMap.getString("domainsOnlyRadioButton.text")); // NOI18N
    domainsOnlyRadioButton.setName("domainsOnlyRadioButton"); // NOI18N
    domainsOnlyRadioButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        domainsOnlyRadioButtonActionPerformed(evt);
      }
    });

    nodeDisplaybuttonGroup.add(addSequencesRadioButton);
    addSequencesRadioButton.setText(resourceMap.getString("addSequencesRadioButton.text")); // NOI18N
    addSequencesRadioButton.setName("addSequencesRadioButton"); // NOI18N
    addSequencesRadioButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addSequencesRadioButtonActionPerformed(evt);
      }
    });

    nodeDisplaybuttonGroup.add(addStructuresRadioButton);
    addStructuresRadioButton.setText(resourceMap.getString("addStructuresRadioButton.text")); // NOI18N
    addStructuresRadioButton.setName("addStructuresRadioButton"); // NOI18N
    addStructuresRadioButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addStructuresRadioButtonActionPerformed(evt);
      }
    });

    displayOptionsLabel.setFont(resourceMap.getFont("displayOptionsLabel.font")); // NOI18N
    displayOptionsLabel.setText(resourceMap.getString("displayOptionsLabel.text")); // NOI18N
    displayOptionsLabel.setName("displayOptionsLabel"); // NOI18N

    jToggleButton1.setText(resourceMap.getString("jToggleButton1.text")); // NOI18N
    jToggleButton1.setName("jToggleButton1"); // NOI18N

    jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
    jLabel1.setName("jLabel1"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(jToggleButton1)
          .addComponent(displayOptionsLabel)
          .addComponent(addStructuresRadioButton)
          .addComponent(addSequencesRadioButton)
          .addComponent(domainsOnlyRadioButton))
        .addContainerGap(286, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addComponent(jLabel1)
        .addGap(181, 181, 181)
        .addComponent(displayOptionsLabel)
        .addGap(3, 3, 3)
        .addComponent(domainsOnlyRadioButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(addSequencesRadioButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(addStructuresRadioButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
        .addComponent(jToggleButton1)
        .addGap(60, 60, 60))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void domainsOnlyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainsOnlyRadioButtonActionPerformed
      // Remove any sequence or structure nodes

    }//GEN-LAST:event_domainsOnlyRadioButtonActionPerformed

    private void addSequencesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSequencesRadioButtonActionPerformed
      // Add sequence nodes

    }//GEN-LAST:event_addSequencesRadioButtonActionPerformed

    private void addStructuresRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStructuresRadioButtonActionPerformed
      // Add 3D structure nodes

    }//GEN-LAST:event_addStructuresRadioButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tmp().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton addSequencesRadioButton;
  private javax.swing.JRadioButton addStructuresRadioButton;
  private javax.swing.JLabel displayOptionsLabel;
  private javax.swing.JRadioButton domainsOnlyRadioButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.ButtonGroup nodeDisplaybuttonGroup;
  // End of variables declaration//GEN-END:variables

}
